### PR TITLE
Bump Features/CONFIG from 2.0.0 to 2.0.2

### PR DESCRIPTION
**Pull request by ProjectMuBot**
Bumps Features/CONFIG from `2.0.0` to `2.0.2`

Introduces 15 new commits in [Features/CONFIG](https://github.com/microsoft/mu_feature_config.git).

<details>
<summary>Commits</summary>
<ul>
<li><a href="https://github.com/microsoft/mu_feature_config/commit/f7351fb88d5eba6d809f58aff216ff5009f12f5b">f7351f</a> GitHub Action: Bump actions/checkout from 3 to 4 (<a href="https://github.com/microsoft/mu_feature_config/pull/233">#233</a>)</li>
<li><a href="https://github.com/microsoft/mu_feature_config/commit/237279c740d967f2b399722a3ea6f6b24942e90e">237279</a> pip: bump antlr4-python3-runtime from 4.13.0 to 4.13.1 (<a href="https://github.com/microsoft/mu_feature_config/pull/234">#234</a>)</li>
<li><a href="https://github.com/microsoft/mu_feature_config/commit/3672705455cf5624516e3254cc7539089ac910de">367270</a> pip: bump pytest from 7.4.0 to 7.4.1 (<a href="https://github.com/microsoft/mu_feature_config/pull/236">#236</a>)</li>
<li><a href="https://github.com/microsoft/mu_feature_config/commit/f768b8ad120c4191d4a5e14b24f5264ffedc69bd">f768b8</a> pip: bump pytest-html from 3.2.0 to 4.0.0 (<a href="https://github.com/microsoft/mu_feature_config/pull/235">#235</a>)</li>
<li><a href="https://github.com/microsoft/mu_feature_config/commit/070a9d7af9123c57dea33db16d98d02c2d58ef21">070a9d</a> pip: bump edk2-pytool-extensions from 0.24.0 to 0.24.1 (<a href="https://github.com/microsoft/mu_feature_config/pull/239">#239</a>)</li>
<li><a href="https://github.com/microsoft/mu_feature_config/commit/c8484375646407e87f826d147739babcbc8c5e6e">c84843</a> pip: bump pytest-html from 4.0.0 to 4.0.1 (<a href="https://github.com/microsoft/mu_feature_config/pull/238">#238</a>)</li>
<li><a href="https://github.com/microsoft/mu_feature_config/commit/81fad9a8505717b902f6279bb35c766a33072abd">81fad9</a> pip: bump pytest from 7.4.1 to 7.4.2 (<a href="https://github.com/microsoft/mu_feature_config/pull/240">#240</a>)</li>
<li><a href="https://github.com/microsoft/mu_feature_config/commit/8c0e50b5c8a443a0395d7bf2ac7948d0e5489f1e">8c0e50</a> Repo File Sync: Update CodeQL GitHub workflow (<a href="https://github.com/microsoft/mu_feature_config/pull/242">#242</a>)</li>
<li><a href="https://github.com/microsoft/mu_feature_config/commit/4da0c03d73815b096e828c5034287003acce8b29">4da0c0</a> Updated auto-gen script to accept cache for policy values (<a href="https://github.com/microsoft/mu_feature_config/pull/244">#244</a>)</li>
<li><a href="https://github.com/microsoft/mu_feature_config/commit/12e78e168e8fa433bf1b17bc9426d5a0769b9d8d">12e78e</a> pip: bump pytest-html from 4.0.1 to 4.0.2 (<a href="https://github.com/microsoft/mu_feature_config/pull/246">#246</a>)</li>
<li><a href="https://github.com/microsoft/mu_feature_config/commit/fc299772f5068855818dc9bcc206228c38f8e7c8">fc2997</a> .pytool/CISettings.py: Update from 202208 to 202302 (<a href="https://github.com/microsoft/mu_feature_config/pull/247">#247</a>)</li>
<li><a href="https://github.com/microsoft/mu_feature_config/commit/757719ae2f2709f4c5c62a3d57c27c9d3831f554">757719</a> pip: bump edk2-pytool-library from 0.17.0 to 0.18.0 (<a href="https://github.com/microsoft/mu_feature_config/pull/245">#245</a>)</li>
<li><a href="https://github.com/microsoft/mu_feature_config/commit/e58f76b437ced0e2fe73f1768eb97625e541adfd">e58f76</a> Repo File Sync: Add cargo ecosystem to dependabot config (<a href="https://github.com/microsoft/mu_feature_config/pull/248">#248</a>)</li>
<li><a href="https://github.com/microsoft/mu_feature_config/commit/e75813037e402ae992e4a21ff0f1d9b93458d4c8">e75813</a> pip: bump xmlschema from 2.4.0 to 2.5.0 (<a href="https://github.com/microsoft/mu_feature_config/pull/250">#250</a>)</li>
<li><a href="https://github.com/microsoft/mu_feature_config/commit/0e8b98c67d019e450762f649f14292f4e386af7a">0e8b98</a> SetupDataPkg: Fix GCC failure in KnobService.py (<a href="https://github.com/microsoft/mu_feature_config/pull/251">#251</a>)</li>
</ul>
</details>

Signed-off-by: Project Mu Bot <mubot@microsoft.com>

### CODE REVIEW

**Comment by kuqin12** [comment]
Taking a look at the build failure now.

**Comment by makubacki** [comment]
> Taking a look at the build failure now.

I actually have a fix I'm verifying now. Just changing some types.

**Comment by kuqin12** [comment]
> > Taking a look at the build failure now.
> 
> I actually have a fix I'm verifying now. Just changing some types.

Thanks! I will hold off then. Please let me know if you need votes on the fix in mu_feature_config.

**Comment by makubacki** [comment]
> > > Taking a look at the build failure now.
> > 
> > 
> > I actually have a fix I'm verifying now. Just changing some types.
> 
> Thanks! I will hold off then. Please let me know if you need votes on the fix in mu_feature_config.

This worked for me locally on GCC5:

https://github.com/microsoft/mu_feature_config/pull/251

**Comment by makubacki** [comment]
Updated PR to move to v2.0.2 to pick up the bug fix.

**Pull request merged**
