### PR TITLE
Use Mu DevOps

### PR DESCRIPTION
**Pull request by makubacki**
Updates this repository to use the consolidated YAML template resources
provided at microsoft/mu_devops for its Azure DevOps pipelines.

The following remaining YAML files build against the latest templates in
mu_devops main branch by defining a repository resource in the YAML
file:
  - .azurepipelines\Ubuntu-GCC5.yml
  - .azurepipelines\Windows-VS.yml
  - Platforms\QemuQ35Pkg\.azurepipelines\Windows-VS.yml
  - Platforms\QemuQ35Pkg\.azurepipelines\Ubuntu-GCC5.yml

These YAML files have been tested to support this repository's builds as
visible in the Project Mu pipelines.

https://dev.azure.com/projectmu/mu/_build

Signed-off-by: Michael Kubacki <michael.kubacki@microsoft.com>

### CODE REVIEW

**Comment by makubacki** [comment]
Note: The build results (with existing pipelines) do not reflect the build results with this change. Please go here to see what the results look like with this PR - [Pipelines/Mu DevOps CI Testing](https://dev.azure.com/projectmu/mu/_build?definitionScope=%5CMu%20DevOps%20CI%20Testing).

**Comment by makubacki** [comment]
OvmfPkg files appeared to be buried way under here: https://github.com/microsoft/mu_tiano_platforms/tree/release/202202/Platforms/OvmfPkg/PlatformCI/.azurepipelines

The pipelines seem broken and inactive for those. Do we care about them? Any problem with me just deleting them from this repo in this PR?

**Comment by apop5** [comment]
Do we have a way to check the last time the pipeline files were functional?

**Review by apop5 — APPROVED** [review]

**Comment by makubacki** [comment]
> Do we have a way to check the last time the pipeline files were functional?

The pipeline historical data for 202202 goes back to August 1st and it was broken then. It's probably been broken for a long time.

@spbrogan disabled the pipelines on 8/22/2022
image

So, this is maintaining status quo and it does not affect our decision process to reenable the OVMF pipelines in the future (other than making it be more converged with what Q35 is using).

**Review by kuqin12 — APPROVED** [review]

**Review by spbrogan — APPROVED** [review]

**Comment by spbrogan** [comment]
Instead of deleting the readme.md in the .azurepipelines file you might want to change it to point to mu_devops repo and provide background on the split between this repo and the common stuff in devops repo.

**Comment by makubacki** [comment]
I forgot about this PR and redid the work in #79. Closing this PR now.

**Pull request closed without merging**
