### PR TITLE
Enable CapsuleLib in Q35

### PR DESCRIPTION
**Pull request by Javagedes**
QemuQ35 uses CapsuleLibNull which causes it to fail the RuntimeServicesTest.MiscRuntimeServicesTest.UpdateCapsule_Conf SCT  as StageCapsuleImage() would always return EFI_UNSUPPORTED. Enabling CapsuleLib allows the normal capsule update process to be evaluated by the SCTs.

### CODE REVIEW

**Comment by makubacki** [comment]
Could you please provide some detail in the PR description?

**Comment by Javagedes** [comment]
> Could you please provide some detail in the PR description?

Updated. Thanks!

**Comment by makubacki** [comment]
@Javagedes, the PR is still targeting release/202202. Do you want that or main now?

**Review by makubacki — APPROVED** [review]

**Comment by Javagedes** [comment]
> @Javagedes, the PR is still targeting release/202202. Do you want that or main now?

main. I've updated as such. Thanks again!

**Comment by Javagedes** [comment]
> > @Javagedes, the PR is still targeting release/202202. Do you want that or main now?
> 
> main. I've updated as such. Thanks again!

@makubacki I need to fix a few conflicts and push a new commit so the pipelines kick off again.

**Comment by Javagedes** [comment]
> > > @Javagedes, the PR is still targeting release/202202. Do you want that or main now?
> > 
> > 
> > main. I've updated as such. Thanks again!
> 
> @makubacki I need to fix a few conflicts and push a new commit so the pipelines kick off again.

Rebased. Pipelines are running.

**Review by makubacki — APPROVED** [review]

**Review by kuqin12 — APPROVED** [review]

**Pull request merged**
