### PR TITLE
Bump MU_BASECORE from 2022080001.4.1 to 2022080002.0.1

### PR DESCRIPTION
**Pull request by ProjectMuBot**
Bumps MU_BASECORE from `2022080001.4.1` to `2022080002.0.1`

Introduces 6 new commits in [MU_BASECORE](https://github.com/microsoft/mu_basecore.git).

<details>
<summary>Commits</summary>
<ul>
<li><a href="https://github.com/microsoft/mu_basecore/commit/9d51733cdc99cf317e23afcb424f09e4dfe0ce01">9d5173</a> Revert "Converge on 4k Section Alignment for AARCH64 Builds" (<a href="https://github.com/microsoft/mu_basecore/pull/391">#391</a>)</li>
<li><a href="https://github.com/microsoft/mu_basecore/commit/0a8242f62f203a4c37eada14c82a07289d057a2f">0a8242</a> Remove the ARM GCC compiler extdeps to use container GCC (<a href="https://github.com/microsoft/mu_basecore/pull/388">#388</a>)</li>
<li><a href="https://github.com/microsoft/mu_basecore/commit/8b00f3fe8358a019e3325208af5b6f42354eb6ea">8b00f3</a> Repo File Sync: Always publish logs in CodeQL workflow, fix container safe dir, add issue assignment workflow (<a href="https://github.com/microsoft/mu_basecore/pull/383">#383</a>)</li>
<li><a href="https://github.com/microsoft/mu_basecore/commit/c3b4b32f42e660a83151a6e4fa5f77eeb29799e1">c3b4b3</a> Fix dmpstore regressed during CodeQL changes (<a href="https://github.com/microsoft/mu_basecore/pull/382">#382</a>)</li>
<li><a href="https://github.com/microsoft/mu_basecore/commit/8ad345f0e8cdac521937f5424e984eba0c13a30c">8ad345</a> MdeModulePkg/Core: Reduce stack cookie value verbosity (<a href="https://github.com/microsoft/mu_basecore/pull/384">#384</a>)</li>
<li><a href="https://github.com/microsoft/mu_basecore/commit/1bd4b3bfd657ad5a3940d072be6540f7c9c23c5d">1bd4b3</a> Converge on 4k Section Alignment for AARCH64 Builds (<a href="https://github.com/microsoft/mu_basecore/pull/352">#352</a>)</li>
</ul>
</details>

Also updates `Features/MM_SUPV` to include an override hash update required
with this Mu Basecore update.

Signed-off-by: Project Mu Bot <mubot@microsoft.com>

### CODE REVIEW

**Comment by makubacki** [comment]
Depends on https://github.com/microsoft/mu_feature_mm_supv/pull/116 for CI to pass

**Comment by makubacki** [comment]
> Depends on [microsoft/mu_feature_mm_supv#116](https://github.com/microsoft/mu_feature_mm_supv/pull/116) for CI to pass

I'll add a commit to this PR to update the MM Supervisor submodule once 116 is completed.

**Comment by makubacki** [comment]
> > Depends on [microsoft/mu_feature_mm_supv#116](https://github.com/microsoft/mu_feature_mm_supv/pull/116) for CI to pass
> 
> I'll add a commit to this PR to update the MM Supervisor submodule once 116 is completed.

Done

**Comment by makubacki** [comment]
@microsoft-github-policy-service agree company="Microsoft"

**Review by apop5 — APPROVED** [review]

**Review by makubacki — APPROVED** [review]

**Review by Javagedes — APPROVED** [review]

**Comment by makubacki** [comment]
@os-d, it looks like commit [1bd4b3b](https://github.com/microsoft/mu_basecore/commit/1bd4b3bfd657ad5a3940d072be6540f7c9c23c5d) increased the size of FVMAIN in the QemuSbsaPkg DEBUG build by ~256KB and it now exceeds the size of FVMAIN_COMPACT (2MB) by ~27KB.

Here's a pipeline where I ran the same content in this PR minus commit `1bd4b3b` - [20230504.3 - MU_BASECORE: Size check](https://dev.azure.com/projectmu/mu/_build/results?buildId=45476&view=results).

Please let me know what you'd like to do or if you'd like to discuss this further.

**Comment by os-d** [comment]
@makubaki, this is an unintended consequence of this this [commit](https://github.com/microsoft/mu_basecore/commit/1bd4b3bfd657ad5a3940d072be6540f7c9c23c5d). I have a revert PR up here: https://github.com/microsoft/mu_basecore/pull/391, while we take more time to debug the [issue](https://github.com/microsoft/mu_basecore/issues/386).

**Pull request merged**
